---
title: "Shifts in Web Surveys Are Accelerating Declines in Response Rates Across the Industry"
title-block-banner: true
#subtitle: "TBD"
thanks: "Available at: https://github.com/TonySun1107/miniessay5.git"
author: "Wentao Sun"
date: today
format: pdf
toc: false
number-sections: true
bibliography: references.bib
---


With the development of technology, the Internet and digital media are gradually becoming an irreplaceable part of people's lives. The network has also been used in statistics in many ways. One of the advantages is that it is easier to circulate questionnaires for more people to fill in than traditional questionnaires. Until now, the only way to get people to answer questions was to communicate with them offline in person, over the phone, or by email. The internet is definitely a better way to distribute survey questions. Not only that, but the web also allows for quick analysis and summarization of the results, so that these results can be visualized in a clear and intuitive way. We failed to increase survey response rates by adding an optional Internet response[@cite4]. The web is not a perfect way to get survey results, and web surveys have exacerbated the decline in response rates across the industry. This phenomenon not only affects the validity and credibility of the survey, but it can also lead to errors in data collection, which can affect the accuracy of the research results. This article has to discuss the overall macro response rate decline and the impact of the web.

The problem of poor response rates to surveys involves a number of factors. This article summarizes some of the major causes of poor survey response rates and discusses possible effective solutions to the problem. By using R [@citeR] as shown below.

The problem of poor response rates to surveys involves a number of factors. This article summarizes some of the major causes of poor survey response rates and discusses possible effective solutions to the problem. First on the list is the issue of privacy, which is a common problem in both traditional surveys and online surveys brought about by new digital media. the participants will respond honestly only if their identity is hidden and confidentiality is maintained[@cite6]. In today's world of data breaches and cybersecurity incidents, the protection of personal information has become increasingly important. Statisticians must consider whether the survey questions will be answered truthfully by people, for example, want to investigate the proportion of drug use among the underage population, when direct questions will make the participants hide their true answers. Because it involves the participants themselves, they may choose to deceive for fear of legal sanctions. Often, in such cases, one should think of changing the question to a more subtle one in order to get the desired answer indirectly. This allows the survey respondent to be more relaxed and protect their privacy during the survey. Surveys digitized on the web will not only face the privacy issues that traditional surveys face, but they will also face the problems of the web altogether. Compared to traditional surveys, web-digitized surveys can pose a threat to the safety of people's lives and property. Not everyone is clear whether a link back will be a well-intentioned social survey or a horrible electronic virus. In this age of information technology, a malicious program script on a cell phone or computer is enough to know any information about a person including bank card passwords, phone numbers, home address and so on. These privacy leaks can threaten people's safety. Filling out one less survey can avoid one more privacy leakage, and most people will choose to do so. So when faced with a digitized survey, they may choose not to participate or fill out the questionnaire incompletely. A reminder mail notification had a positive effect on response rate for the Web survey application compared to a treatment in which respondents only received an e-mail containing a link to the Web survey[@cite3]. Sending survey invitations as reminders makes participants less resistant to emails, although there is still a risk of information leakage. This is one of the reasons why the internet is one of the reasons why response rates have dropped.

The second reason for the decline in survey response rates is the lack of incentives. Participation in surveys is a time-consuming activity with no benefits, and public interest or social surveys are not enough to motivate people to participate in them wholeheartedly. Participants perceive that the time and effort involved in participating far outweighs the benefits they receive, and they are likely not to participate. This problem occurs in both traditional surveys and online digital surveys. Furthermore, vouchers seem to be the most effective incentive in long questionnaires, while lotteries are more efficient in short surveys[@cite2]. In some cases, offering the right incentives (e.g., gift cards, cash prizes, etc.) can increase participant motivation, which can significantly increase survey response rates.

Another major cause of poor survey response rates is Survey Fatigue. With the popularity of the Internet and digital media, individuals receive many invitations to surveys every day from different sources, and survey links are constantly pouring in on cell phones and computers. These include survey publishers that have member brands, registered websites, randomly sent to a company, and so on. Surveys may be pushed along with commercial advertisements, which makes participants lose their ability to recognize them. Social and public interest surveys are often mixed with commercial surveys. These excessive surveys do not lead to good results. Such excessive survey requests cause people to feel tired of the questionnaire and even resistant to it, thus reducing the desire to answer. Faced with a large number of survey invitations, they choose to ignore them or answer them perfunctorily. This is the main reason for the drop in response and completion rates. Keeping surveys short and to the point is key, as this makes it easier to grab the attention of participants and keep them interested in a survey. Not only should you make sure that the survey invitation is simple to follow, but you should also make sure that each question is concise and direct. This will make it easier for participants to answer the survey for data collection purposes.

Increasing the response rate to surveys requires careful planning and a combination of question design, privacy, and reward methods. Questionnaire design and development must be supported by a logical, systematic and structured approach[@cite5]. Taken together to allay participants' concerns about the survey, the act of clearly informing participants about how their data will be collected and utilized, and ensuring the anonymity and security of the survey data can alleviate participants' privacy concerns. Secondly ensure that the content of the survey is closely related to the interests of the target audience, and if this is not possible then offer more reasonable incentives to encourage more people to participate. This will also increase their willingness to participate and increase the response rate. Quality and accurate survey data will help in rule making and the development of society.

\newpage
#References
